export const SETUSER = 'SETUSER';
export const UPLOADAVATAR = 'UPLOADAVATAR';
export const REMOVEUSER = 'REMOVEUSER';
export const INCRETOCART = 'INCRETOCART';
export const DECRETOCART = 'DECRETOCART';
export const REMOVETOCART = 'REMOVETOCART';
export const CLEARTOCART = 'CLEARTOCART';
export const SETPAYMENT = 'SETPAYMENT';